### PR TITLE
fix: add webhook readiness check to hub-agent

### LINKED ISSUE #404: [BUG] E2E tests fail with webhook connection refused during MemberCluster creation
### **Describe the bug**

E2E tests fail with "connection refused" when creating MemberCluster objects because the validating webhook is not ready to serve requests. The hub-agent pod is marked ready before the webhook configuration is created and the webhook server is listening.

```
Internal error occurred: failed calling webhook "fleet.membercluster.validating":
failed to call webhook: Post "https://fleetwebhook.fleet-system.svc:9443/validate-cluster.kubernetes-fleet.io-v1beta1-membercluster?timeout=5s":
dial tcp 10.96.27.105:9443: connect: connection refused
```

### **Environment**
 
- Hub cluster details: Kind cluster (kindest/node:v1.33.4), hub-agent deployed via Helm
- Member cluster details: 3 Kind clusters (cluster-1, cluster-2, cluster-3)

### **To Reproduce**

1. Run `make clean-e2e-tests && make e2e-tests`
2. Tests fail at `SynchronizedBeforeSuite` when attempting to create MemberCluster objects
3. Webhook service refuses connections at `fleetwebhook.fleet-system.svc:9443`

### **Expected behavior**

The hub-agent pod should only be marked ready after the webhook server is listening and webhook configurations (ValidatingWebhookConfiguration, MutatingWebhookConfiguration) are created in the API server. E2E tests should be able to create MemberCluster objects without webhook connection errors.

### **Screenshots**
N/A

### **Additional context**

The issue occurs because:
1. `setup.sh` completes helm install but doesn't wait for hub-agent deployment readiness
2. Hub-agent pod passes basic health checks and is marked ready
3. E2E tests start immediately and try to create MemberCluster
4. API server calls the webhook, but it's not yet serving

Potential fixes:
- Add `kubectl rollout status deployment/hub-agent -n fleet-system --timeout=2m` to `setup.sh` after helm install
- Add webhook readiness check to hub-agent so pod isn't ready until webhook configurations exist

### PR DESCRIPTION
**Pull request by ytimocin**
### Description of your changes

This pull request introduces a readiness check for the webhook component in the hub agent, ensuring that the pod is not marked as ready until the webhook configurations have been successfully created in the API server. This improves the reliability of the deployment by preventing premature readiness signaling. Additional unit tests are added to verify the new readiness logic, and the e2e setup script is updated to wait for the deployment to become ready.

**Webhook readiness improvements:**

* Modified `SetupWebhook` in `cmd/hubagent/main.go` to return the webhook `Config` object and register a readiness check using its `ReadinessChecker` method, ensuring the pod only becomes ready after webhook configuration is complete. [[1]](diffhunk://#diff-dc12684f7ab370528e17e7340358c0614e725ed43fac7b7af203a6d79667e5c2L161-R172) [[2]](diffhunk://#diff-dc12684f7ab370528e17e7340358c0614e725ed43fac7b7af203a6d79667e5c2R211-R228)
* Added an atomic `ready` flag to the `Config` struct in `pkg/webhook/webhook.go`, set to `true` after successful webhook configuration, and implemented the `ReadinessChecker` method to expose this as a health check. [[1]](diffhunk://#diff-df64e37f2222b761c62bd8bf32c0347aae0fe1f46ff6acf0e66c2b61bd30d761R167-R169) [[2]](diffhunk://#diff-df64e37f2222b761c62bd8bf32c0347aae0fe1f46ff6acf0e66c2b61bd30d761R203-R217)

**Testing enhancements:**

* Added unit tests in `pkg/webhook/webhook_test.go` to verify the readiness checker logic, including concurrent access scenarios.

**Deployment reliability:**

* Updated `test/e2e/setup.sh` to explicitly wait for the `hub-agent` deployment (including the webhook) to become ready before proceeding.

**Test code refactoring:**

* Changed test case maps in `pkg/webhook/webhook_test.go` to use pointers, improving test code consistency. [[1]](diffhunk://#diff-54553ccca2e329f7bf1fdf04d002ced7323d3fa477e7fc6e2a0a9d248cb10ab2L17-R18) [[2]](diffhunk://#diff-54553ccca2e329f7bf1fdf04d002ced7323d3fa477e7fc6e2a0a9d248cb10ab2L44-R45) [[3]](diffhunk://#diff-54553ccca2e329f7bf1fdf04d002ced7323d3fa477e7fc6e2a0a9d248cb10ab2L79-R80)

Fixes #404 

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

By running e2e tests with and w/o the changes.

### Special notes for your reviewer

N/A

### CODE REVIEW

File: test/e2e/setup.sh [hunk 1]
```diff
@@ -132,6 +132,10 @@ helm install hub-agent ../../charts/hub-agent/ \
     --set resourceSnapshotCreationMinimumInterval=$RESOURCE_SNAPSHOT_CREATION_MINIMUM_INTERVAL \
     --set resourceChangesCollectionDuration=$RESOURCE_CHANGES_COLLECTION_DURATION
 
+# Wait for hub-agent deployment to be ready (includes webhook)
+echo "Waiting for hub-agent deployment to be ready..."
+kubectl rollout status deployment/hub-agent -n fleet-system --timeout=2m
```
Comment (weng271190436) [inline test/e2e/setup.sh]: you can do this with the helm install options --wait and --timeout so that you don't need a separate command?

File: pkg/webhook/webhook.go [hunk 2]
```diff
@@ -195,9 +200,22 @@ func (w *Config) Start(ctx context.Context) error {
 		klog.ErrorS(err, "unable to setup webhook configurations in apiserver")
 		return err
 	}
+	w.ready.Store(true)
```
Comment (weng271190436) [inline pkg/webhook/webhook.go]: I think this does not solve the issue: #404 

You are observing

```txt
Internal error occurred: failed calling webhook "fleet.membercluster.validating":
failed to call webhook: Post "[https://fleetwebhook.fleet-system.svc:9443/validate-cluster.kubernetes-fleet.io-v1beta1-membercluster?timeout=5s](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)":
dial tcp 10.96.27.105:9443: connect: connection refused
```

this means that the webhook was registered and k8s api server knows about it. Otherwise the api server won't know that there is a webhook "fleet.membercluster.validating" to call

I searched a bit and it seems that the webhook server's started checker (which is a built-in health checker) is one way to do it

https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/webhook#DefaultServer.StartedChecker 

```go
wh := mgr.GetWebhookServer()
wh.StartedChecker()
```

File: pkg/webhook/webhook_test.go [hunk 3]
```diff
@@ -22,7 +22,7 @@ import (
 
 func TestBuildFleetMutatingWebhooks(t *testing.T) {
 	url := options.WebhookClientConnectionType("url")
-	testCases := map[string]struct {
+	testCases := map[string]*struct {
```
Comment (weng271190436) [inline pkg/webhook/webhook_test.go]: why do we change this to *struct?

**Review by weng271190436 — APPROVED** [review]

**Comment by ytimocin** [comment]
> ## [Codecov](https://app.codecov.io/gh/kubefleet-dev/kubefleet/pull/407?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubefleet-dev) Report
> ❌ Patch coverage is `0%` with `1 line` in your changes missing coverage. Please review.
> 
> [Files with missing lines](https://app.codecov.io/gh/kubefleet-dev/kubefleet/pull/407?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubefleet-dev)	Patch %	Lines
> [pkg/webhook/webhook.go](https://app.codecov.io/gh/kubefleet-dev/kubefleet/pull/407?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubefleet-dev#diff-cGtnL3dlYmhvb2svd2ViaG9vay5nbw==)	0.00%	[1 Missing ⚠️ ](https://app.codecov.io/gh/kubefleet-dev/kubefleet/pull/407?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=kubefleet-dev)
> 📢 Thoughts on this report? [Let us know!](https://github.com/codecov/feedback/issues/255)

The uncovered line is a log statement; webhook setup is validated through E2E tests.
